name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Copy files to VM
      run: |
        rsync -avz -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          --delete ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/Quiz
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
    
    - name: Restart app on VM
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
          ${{ secrets.USER }}@${{ secrets.HOST }} \
          "cd /home/${{ secrets.USER }}/Quiz && echo 'Files copied successfully to Quiz folder'"